### ISSUE TITLE
개발일정

### ISSUE THREAD

**Issue by hyunjong-lee** [lache/john#4]
- ~ 1월 7일: 데이터 및 기본 기술 조사
- ~ 1월 14일: 가장 간단한 봇 만들기 - 유우머 봇처럼 시간 떼우기 좋은 용도로
- ~ 1월 21일: 사용자 반응을 보며 고도화, 머신러닝 모델링 시작
- ~ 1월 28일: 데이터가 쌓여있다면 분석, 머신러닝 모델링 계속
- ~ 1월 30일: [설날 주간] 머신러닝 모델 적용
- ~ 2월 5일: 여태까지 작업한 것 회고
- ~ 2월 12일: TBD
- ~ 2월 19일: TBD

**Comment by hyunjong-lee** [comment]
우린 망햇어 ㅠ.ㅠ

**Comment by gasbank** [comment]
ㅠ.ㅠ
